#!/bin/sh
#
#
# Notice! This file is controlled by Chef, do not edit this file directly on the client as it will be rest by chef the next time chef runs.
#
#

/usr/sbin/logrotate /etc/logrotate.conf
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
