	 
#!/bin/sh
#
# Notice! This file is controlled by Chef, do not edit this file directly on the client as it will be rest by chef the next time chef runs.
#
#
# Script backups files from a remote location to a local folder with a rsync making your box into a backup server.
# In the end you will end up with 7 day rotating incremental backup of your files. 
########################################################################
# BACKUPDIR=`date +%A` OPTS="--force --ignore-errors --delete-excluded 
# 	--exclude-from=$EXCLUDES --delete --backup --backup-dir=/$BACKUPDIR -a" export 
########################################################################################
#############
PATH=$PATH:/bin:/usr/bin:/usr/local/bin
OPTS="--backup --filter='- .rsync-filter' --bwlimit=3000 -aveXr "
RPROTO="ssh"
clear
echo
echo 'Starting the pulling of backups/rsnapshots...'
echo spath $PATH
echo
BIOLIMIT=2000
BACKUPDIR=`date +%A`
BTARGET=192.168.178.13
BEXCLUDES='--exclude=/proc/ --exclude=/var/cache/ --exclude=/sys/ --exclude=/tmp/ --exclude=/var/lock/*.pid 
	--exclude=/etc/selinux/targeted/ --exclude=/backups/ --exclude=/var/lib/mlocate/ 
	--exclude=/var/lib/yum/history/ --exclude=/var/lib/yum/yumdb/ --exclude=/var/spool/squid3/ --exclude=/media/ --exclude=/home/osmc/.kodi/userdata/Thumbnails/ --exclude=home/osmc/.kodi/temp/*'
# BLOCATION='/media/98DCAB06DCAADDAE/rsnapshot/barebones/osmc/'
BLOCATION='/backups/local/'
echo
echo
echo 'Pulling files from' $BTARGET  and are writen to  $BLOCATION$BACKUPDIR
echo
echo Excluding the following locations $BEXCLUDES
echo
echo Limit I/O $BIOLIMIT kbps
echo Rsync options 
echo
SLEEP=10

# Now Pull everything 
rsync -aveXr --delete --force --delete-excluded --backup --filter='- .rsync-filter' $BEXCLUDES --bwlimit=$BIOLIMIT --progress --delete --rsh="ssh -p 22 -o StrictHostKeyChecking=no -o ConnectTimeout=10 -o ServerAliveInterval=60" root@$BTARGET:/ $BLOCATION$BACKUPDIR |tee $BLOCATION/$BACKUPDIR-rsync.log
